### ISSUE TITLE
Direct browser support missing

### ISSUE THREAD

**Issue by benhovinga** [benhovinga/caf-ranks#16]
Tried adding this script to an HTML document and it did not work as expected.

```html
<script src="https://cdn.jsdelivr.net/npm/caf-ranks@0.6.0/dist/main.js"></script>
```

```console
Uncaught ReferenceError: exports is not defined at main.js:5:23
```

**Comment by benhovinga** [comment]
#### Test 1

```html
<script type="module">
  import cafRanks from "//cdn.jsdelivr.net/npm/caf-ranks@0.6.0/dist/main.js";
  console.log(cafRanks);
</script>
```

```console
Uncaught SyntaxError: The requested module '//cdn.jsdelivr.net/npm/caf-ranks@0.6.0/dist/main.js' does not provide an export named 'default' (at (index):59:14)
```

#### Test 2

```html
<script type="module">
  import { allRanks } from "//cdn.jsdelivr.net/npm/caf-ranks@0.6.0/dist/main.js";
  console.log(allRanks);
</script>
```

```console
Uncaught SyntaxError: The requested module '//cdn.jsdelivr.net/npm/caf-ranks@0.6.0/dist/main.js' does not provide an export named 'allRanks' (at (index):59:16)
```

#### Test 3

```html
<script type="module" src="//cdn.jsdelivr.net/npm/caf-ranks@0.6.0/dist/main.js">
  console.log(allRanks);
</script>
```

```console
Uncaught ReferenceError: exports is not defined at main.js:5:23
```

#### Test 4

```html
<script type="module">
  import * as cafRanks from "//cdn.jsdelivr.net/npm/caf-ranks@0.6.0/dist/main.js";
  console.log(cafRanks);
</script>
```

```console
Uncaught ReferenceError: exports is not defined at main.js:5:23
```
